# Generated by Django 4.2.4 on 2024-06-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1080)),
                ('slug', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('featured', models.BooleanField(default=False)),
                ('thumbnail', models.CharField(max_length=2000)),
            ],
        ),
    ]
